### ISSUE TITLE
can no longer read in parquet files from GH release

### ISSUE THREAD

**Issue by erikarasnick** [cole-brokamp/dpkg#4]
```
dpkg::stow("https://github.com/geomarker-io/parcel/releases/download/cagis_parcels-v1.1.0/cagis_parcels-v1.1.0.parquet") |>
  dpkg::read_dpkg() 
```

gives this error 

```
! parquet file does not appear to contain an R object
```

which is coming from `read_dpkg_metadata()`

Could this have to do with saving the parquet file with nanoparquet then changing to now trying to read with arrow? If I run `arrow::open_dataset` on that file directly, `x_a$metadata` says it is a named list, but all fields are NULL. 

```
> x_a$metadata$r$attributes$class
NULL
> x_a$metadata$r$attributes
NULL
> x_a$metadata$r
NULL
> x_a$metadata
named list()
```

**Comment by cole-brokamp** [comment]
Yes, this is definitely due to changing how parquet files are written.  When I switched to just using arrow package so we could do geoparquet files, I moved on from using the nanoparquet file.  Unfortunately, we will need to re-release these files.  But the good news is that using arrow to write the parquet files will ensure that we don't have this issue again in the future.

**Comment by cole-brokamp** [comment]
nanoparquet keeps the metadata in a different place within the R structure it reads in, so it will fail to find the metadata in the right place.

Another advantage to arrow is that it remembers the attributes of the object you put in, so we won't need to feed in the metadata and create a new dpkg object.  Just reading the object in the `arrow::open_dataset` or read_parquet *should* result in a dpkg object being read in without having to use `read_dpkg()`.
